# Generated by Django 3.1.3 on 2021-08-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddcourseT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(default='COURSE_NAME', max_length=200)),
                ('cgrade', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='AddquestionT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cquestion', models.CharField(default='Question', max_length=500)),
            ],
        ),
    ]
