# Generated by Django 3.1.3 on 2021-08-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20210821_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(default='Question', max_length=500)),
                ('subname', models.CharField(default='Question', max_length=500)),
                ('grade', models.CharField(default='Question', max_length=500)),
                ('markobtained', models.CharField(default='Question', max_length=500)),
                ('totalmarks', models.CharField(default='Question', max_length=500)),
            ],
        ),
    ]
