# Generated by Django 3.1.3 on 2021-08-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_quizanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='grade',
            field=models.CharField(default='10', max_length=500),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='markobtained',
            field=models.CharField(default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='studentname',
            field=models.CharField(default='Stud_0', max_length=500),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='subname',
            field=models.CharField(default='sub_0', max_length=500),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='totalmarks',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
