# Generated by Django 3.1.3 on 2021-09-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_mockanswer_mockpm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockAnswer',
        ),
    ]
