# Generated by Django 3.1.3 on 2021-10-08 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_delete_mockanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assesedanswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='id', max_length=10)),
                ('testname', models.CharField(default='sub_0', max_length=500)),
                ('semail', models.CharField(default='studentemail', max_length=200)),
                ('correctedanswersheet', models.FileField(default='static/images/default.pdf', upload_to='images')),
                ('markobtained', models.IntegerField(default='0')),
                ('evaluated', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
