# Generated by Django 3.1.3 on 2021-10-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_assesedanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assesedanswer',
            name='evaluated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='assesedanswer',
            name='markobtained',
            field=models.IntegerField(default=0),
        ),
    ]
