# Generated by Django 3.1.3 on 2021-10-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_auto_20211008_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='assesedanswer',
            name='studentname',
            field=models.CharField(default='Stud_0', max_length=500),
        ),
    ]
