# Generated by Django 3.1.3 on 2021-08-20 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addquestiont',
            options={'ordering': ['cquestion']},
        ),
        migrations.AddField(
            model_name='addquestiont',
            name='testgrade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teacher.addcourset'),
            preserve_default=False,
        ),
    ]
