# Generated by Django 3.1.3 on 2021-08-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20210821_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='addquestiont',
            name='coption1',
            field=models.CharField(default='Option1', max_length=500),
        ),
        migrations.AddField(
            model_name='addquestiont',
            name='coption2',
            field=models.CharField(default='Option2', max_length=500),
        ),
        migrations.AddField(
            model_name='addquestiont',
            name='coption3',
            field=models.CharField(default='Option3', max_length=500),
        ),
        migrations.AddField(
            model_name='addquestiont',
            name='coption4',
            field=models.CharField(default='Option4', max_length=500),
        ),
    ]
