# Generated by Django 3.1.3 on 2021-08-21 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_addquestiont_canswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addquestiont',
            name='canswer',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
