# Generated by Django 3.1.3 on 2021-09-23 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20210822_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(default='Stud_0', max_length=500)),
                ('testname', models.CharField(default='sub_0', max_length=500)),
                ('grade', models.IntegerField()),
                ('markobtained', models.CharField(default='0', max_length=500)),
                ('totalmarks', models.CharField(default='0', max_length=500)),
                ('answersheet', models.FileField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='MockPM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mockpapername', models.CharField(max_length=200)),
                ('paperdescription', models.CharField(default='The description', max_length=100)),
                ('mpgrade', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(10)])),
                ('mockpaper', models.FileField(upload_to='images')),
                ('totalmarks', models.IntegerField(default=0)),
            ],
        ),
    ]
