# Generated by Django 3.1.3 on 2021-10-08 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_auto_20211008_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addquestiont',
            name='canswer',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
    ]
