# Generated by Django 3.1.3 on 2022-01-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_addquizt_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockpm',
            name='addedby',
            field=models.CharField(default='admin', max_length=500),
        ),
    ]
