# Generated by Django 3.1.3 on 2022-01-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0017_mockpm_addedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockpm',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
