# Generated by Django 3.1.3 on 2022-01-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0018_mockpm_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='addquizt',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
