# Generated by Django 3.1.3 on 2022-01-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0019_addquizt_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockpm',
            name='mockpaper',
            field=models.FileField(default='static/images/default.pdf', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='mockpm',
            name='mockpapername',
            field=models.CharField(default='paper name', max_length=200),
        ),
    ]
