# Generated by Django 3.1.3 on 2022-09-21 16:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0020_auto_20220131_0113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addcompexam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(default='competitive exam name', max_length=200)),
                ('author', models.CharField(default='teacher_name', max_length=200)),
                ('cgrade', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(10)])),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Addcompquestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cquestion', models.CharField(default='Question', max_length=500)),
                ('cimg', models.ImageField(default='images/tst2.jpg', upload_to='images')),
                ('cimgadded', models.BooleanField(default=False)),
                ('coption1', models.CharField(default='Option1', max_length=500)),
                ('coption2', models.CharField(default='Option2', max_length=500)),
                ('coption3', models.CharField(default='Option3', max_length=500)),
                ('coption4', models.CharField(default='Option4', max_length=500)),
                ('canswer', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('testgrade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.addcompexam')),
            ],
            options={
                'ordering': ['cquestion'],
            },
        ),
    ]
