# Generated by Django 3.1.3 on 2022-09-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0021_addcompexam_addcompquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcompexam',
            name='negativemarkings',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='addcompexam',
            name='time',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='addcompexam',
            name='totalmarks',
            field=models.IntegerField(default=360),
        ),
    ]
