# Generated by Django 3.1.3 on 2022-09-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0022_auto_20220921_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='TSmessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='sender', max_length=100)),
                ('reciever', models.CharField(default='sender', max_length=100)),
                ('sendername', models.CharField(default='sendername', max_length=100)),
                ('message', models.CharField(default='message', max_length=10000)),
            ],
        ),
    ]
