# Generated by Django 3.1.2 on 2021-11-06 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Some event', max_length=200)),
                ('desc', models.CharField(default='about event', max_length=300)),
                ('Date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
