# Generated by Django 3.1.3 on 2021-11-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0002_onlinecourses_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=1000)),
                ('grade', models.CharField(max_length=150)),
                ('thumbnail', models.ImageField(default='images/tst2.jpg', upload_to='images')),
            ],
        ),
    ]
