# Generated by Django 3.1.3 on 2021-11-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0003_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='description',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
