# Generated by Django 3.1.3 on 2021-11-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0005_auto_20211106_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('thumbnail', models.ImageField(default='images/tst2.jpg', upload_to='images')),
                ('link', models.CharField(max_length=1000)),
                ('isvideo', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=1500)),
                ('istext', models.BooleanField(default=False)),
                ('tipfile', models.FileField(blank=True, upload_to='')),
                ('isfile', models.BooleanField(default=False)),
            ],
        ),
    ]
