# Generated by Django 3.1.3 on 2021-11-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0006_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
