# Generated by Django 3.1.3 on 2021-11-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0007_auto_20211106_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='grade',
            field=models.IntegerField(default=12),
        ),
    ]
