# Generated by Django 3.1.3 on 2021-11-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0008_tips_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('thumbnail', models.ImageField(default='images/tst2.jpg', upload_to='images')),
                ('grade', models.IntegerField(default=10)),
                ('file', models.FileField(default='images/default.pdf', upload_to='images')),
            ],
        ),
    ]
