# Generated by Django 3.1.2 on 2021-11-08 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0009_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='sub',
            field=models.CharField(default='maths', max_length=100),
        ),
        migrations.AlterField(
            model_name='notes',
            name='grade',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(10)]),
        ),
    ]
