# Generated by Django 3.1.3 on 2021-11-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0010_auto_20211108_1658'),
        ('other', '0010_auto_20211108_1720'),
    ]

    operations = [
    ]
