# Generated by Django 3.1.3 on 2022-01-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0011_merge_20211108_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecourses',
            name='addedby',
            field=models.CharField(default='ADMIN', max_length=1000),
        ),
        migrations.AddField(
            model_name='onlinecourses',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
