# Generated by Django 3.1.3 on 2022-01-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0013_auto_20220126_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinecourses',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
