# Generated by Django 3.1.3 on 2022-01-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0014_auto_20220126_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinecourses',
            name='description',
            field=models.CharField(default='course_description', max_length=1500),
        ),
        migrations.AlterField(
            model_name='onlinecourses',
            name='link',
            field=models.CharField(default='/', max_length=1000),
        ),
        migrations.AlterField(
            model_name='onlinecourses',
            name='name',
            field=models.CharField(default='course_name', max_length=150),
        ),
        migrations.AlterField(
            model_name='onlinecourses',
            name='price',
            field=models.CharField(default='FREE', max_length=100),
        ),
    ]
