# Generated by Django 3.1.3 on 2022-09-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0015_auto_20220201_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='images/tst2.jpg', upload_to='images')),
                ('contactname', models.CharField(max_length=100)),
                ('contactnumber', models.CharField(max_length=20)),
                ('brief', models.CharField(max_length=1000)),
            ],
        ),
    ]
