# Generated by Django 3.1.3 on 2021-06-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseArts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(default='images/tst2.jpg', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCommerce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(default='images/tst2.jpg', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='CourseEngineering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(default='images/tst2.jpg', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='CourseProfessional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(default='images/tst2.jpg', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='CourseScience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(default='images/tst2.jpg', upload_to='images')),
            ],
        ),
    ]
