# Generated by Django 3.1.3 on 2021-06-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseProfessional',
            new_name='Art',
        ),
        migrations.RenameModel(
            old_name='CourseCommerce',
            new_name='Commerce',
        ),
        migrations.RenameModel(
            old_name='CourseEngineering',
            new_name='Engineering',
        ),
        migrations.RenameModel(
            old_name='CourseArts',
            new_name='Professional',
        ),
        migrations.RenameModel(
            old_name='CourseScience',
            new_name='Science',
        ),
    ]
