# Generated by Django 3.1.3 on 2021-08-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210629_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
