# Generated by Django 3.1.2 on 2021-11-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_tcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='desc',
            field=models.CharField(default='about', max_length=400),
        ),
        migrations.AddField(
            model_name='commerce',
            name='desc',
            field=models.CharField(default='about', max_length=400),
        ),
        migrations.AddField(
            model_name='engineering',
            name='desc',
            field=models.CharField(default='about', max_length=400),
        ),
        migrations.AddField(
            model_name='professional',
            name='desc',
            field=models.CharField(default='about', max_length=400),
        ),
        migrations.AddField(
            model_name='science',
            name='desc',
            field=models.CharField(default='about', max_length=400),
        ),
    ]
