# Generated by Django 3.1.2 on 2021-11-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20211107_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='duration',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='commerce',
            name='duration',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='engineering',
            name='duration',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='professional',
            name='duration',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='science',
            name='duration',
            field=models.IntegerField(default=3),
        ),
    ]
