# Generated by Django 3.1.3 on 2021-08-17 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QPM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentpaperfile', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('papertype', models.CharField(default='Practise papeR', max_length=200)),
                ('key', models.CharField(default='VieW', max_length=200)),
                ('year', models.CharField(default='UnknowN', max_length=200)),
                ('paper', models.FileField(default='images/none.pdf', upload_to='images')),
                ('childpaperfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quespaper.qpm')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
