# Generated by Django 3.1.3 on 2021-08-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quespaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpm',
            name='description',
            field=models.CharField(default='The description', max_length=100),
        ),
    ]
