# Generated by Django 3.1.3 on 2021-09-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quespaper', '0003_mockpm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockPM',
        ),
    ]
