# Generated by Django 3.1.3 on 2021-11-29 18:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quespaper', '0005_paper_forgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpm',
            name='forgrade',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(10)]),
        ),
    ]
