# Generated by Django 3.1.3 on 2022-01-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quespaper', '0006_qpm_forgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
