# Generated by Django 3.1.3 on 2022-01-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quespaper', '0007_paper_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='addedby',
            field=models.CharField(default='ADMIN', max_length=1000),
        ),
    ]
