# Generated by Django 3.1.3 on 2021-07-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allcollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(default='-', max_length=200)),
                ('state', models.CharField(default='-', max_length=200)),
                ('img', models.ImageField(default='images/tst2.jpg', upload_to='images')),
                ('link', models.CharField(default='#', max_length=200)),
                ('detail', models.CharField(default='UNKNOWN', max_length=200)),
                ('rating', models.CharField(default='NULL', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Citycollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(default='-', max_length=200)),
                ('state', models.CharField(default='-', max_length=200)),
                ('img', models.ImageField(default='images/tst2.jpg', upload_to='images')),
                ('link', models.CharField(default='#', max_length=200)),
                ('detail', models.CharField(default='UNKNOWN', max_length=200)),
                ('rating', models.CharField(default='NULL', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coursebasedcollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(default='-', max_length=200)),
                ('state', models.CharField(default='-', max_length=200)),
                ('img', models.ImageField(default='images/tst2.jpg', upload_to='images')),
                ('link', models.CharField(default='#', max_length=200)),
                ('detail', models.CharField(default='UNKNOWN', max_length=200)),
                ('rating', models.CharField(default='NULL', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Degreecollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(default='-', max_length=200)),
                ('state', models.CharField(default='-', max_length=200)),
                ('img', models.ImageField(default='images/tst2.jpg', upload_to='images')),
                ('link', models.CharField(default='#', max_length=200)),
                ('detail', models.CharField(default='UNKNOWN', max_length=200)),
                ('rating', models.CharField(default='NULL', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Statecollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(default='-', max_length=200)),
                ('state', models.CharField(default='-', max_length=200)),
                ('img', models.ImageField(default='images/tst2.jpg', upload_to='images')),
                ('link', models.CharField(default='#', max_length=200)),
                ('detail', models.CharField(default='UNKNOWN', max_length=200)),
                ('rating', models.CharField(default='NULL', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topcollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(default='-', max_length=200)),
                ('state', models.CharField(default='-', max_length=200)),
                ('img', models.ImageField(default='images/tst2.jpg', upload_to='images')),
                ('link', models.CharField(default='#', max_length=200)),
                ('detail', models.CharField(default='UNKNOWN', max_length=200)),
                ('rating', models.CharField(default='NULL', max_length=200)),
            ],
        ),
    ]
