# Generated by Django 3.1.3 on 2022-09-08 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commname', models.CharField(default='commname', max_length=200)),
                ('comgrade', models.CharField(default='commgrade', max_length=200)),
                ('commcreatedby', models.CharField(default='createdby', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='message', max_length=200)),
                ('madeby', models.CharField(default='sender', max_length=200)),
                ('madebymail', models.CharField(default='sendermail', max_length=200)),
                ('communitytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community')),
            ],
        ),
    ]
