# Generated by Django 3.1.3 on 2022-09-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['communitytype']},
        ),
    ]
