# Generated by Django 3.1.3 on 2022-09-11 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20220911_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['communitytype']},
        ),
        migrations.AlterField(
            model_name='chat',
            name='communitytype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community'),
        ),
    ]
