# Generated by Django 3.1.3 on 2022-09-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20220911_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='commicon',
            field=models.ImageField(default='images/tst2.jpg', upload_to=''),
        ),
    ]
