# Generated by Django 3.1.3 on 2021-08-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customuser_profpic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profpic',
            new_name='img',
        ),
    ]
