# Generated by Django 3.1.3 on 2021-09-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser_hide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thought', models.CharField(max_length=250)),
                ('approval', models.BooleanField(default=False)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
