# Generated by Django 3.1.3 on 2022-09-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dialogues'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='advertise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='needassist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='resume',
            field=models.FileField(default='images/default.pdf', upload_to=''),
        ),
    ]
