# Generated by Django 3.1.3 on 2022-09-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_customuser_contactnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='upgreq',
            field=models.BooleanField(default=False),
        ),
    ]
