# Generated by Django 3.1.3 on 2021-06-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleven',
            name='url',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='ten',
            name='url',
            field=models.CharField(default='#', max_length=200),
        ),
        migrations.AddField(
            model_name='twelve',
            name='url',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
