# Generated by Django 3.1.3 on 2021-06-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210630_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jeeadvance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(default='#', max_length=200)),
                ('img', models.ImageField(default='images/tst2.jpg', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Jeemain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(default='#', max_length=200)),
                ('img', models.ImageField(default='images/tst2.jpg', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Neet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(default='#', max_length=200)),
                ('img', models.ImageField(default='images/tst2.jpg', upload_to='images')),
            ],
        ),
    ]
