# Generated by Django 3.1.3 on 2021-06-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_jeeadvance_jeemain_neet'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleven',
            name='upload_file',
            field=models.FileField(default='images/none.pdf', upload_to='images'),
        ),
        migrations.AddField(
            model_name='jeeadvance',
            name='upload_file',
            field=models.FileField(default='images/none.pdf', upload_to='images'),
        ),
        migrations.AddField(
            model_name='jeemain',
            name='upload_file',
            field=models.FileField(default='images/none.pdf', upload_to='images'),
        ),
        migrations.AddField(
            model_name='neet',
            name='upload_file',
            field=models.FileField(default='images/none.pdf', upload_to='images'),
        ),
        migrations.AddField(
            model_name='ten',
            name='upload_file',
            field=models.FileField(default='images/none.pdf', upload_to='images'),
        ),
        migrations.AddField(
            model_name='twelve',
            name='upload_file',
            field=models.FileField(default='images/none.pdf', upload_to='images'),
        ),
    ]
