# Generated by Django 3.1.3 on 2021-06-30 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210630_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eleven',
            old_name='upload_file',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='jeeadvance',
            old_name='upload_file',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='jeemain',
            old_name='upload_file',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='neet',
            old_name='upload_file',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='ten',
            old_name='upload_file',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='twelve',
            old_name='upload_file',
            new_name='book',
        ),
    ]
