# Generated by Django 3.1.3 on 2021-07-02 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210630_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleven',
            name='book',
        ),
        migrations.RemoveField(
            model_name='jeeadvance',
            name='book',
        ),
        migrations.RemoveField(
            model_name='jeemain',
            name='book',
        ),
        migrations.RemoveField(
            model_name='neet',
            name='book',
        ),
        migrations.RemoveField(
            model_name='ten',
            name='book',
        ),
        migrations.RemoveField(
            model_name='twelve',
            name='book',
        ),
    ]
