# Generated by Django 3.1.3 on 2021-08-17 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210703_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('btype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.booktypes')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
