# Generated by Django 3.1.3 on 2021-08-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_books_booktypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='subject',
            field=models.CharField(default='10,11,12,Main,Neet...', max_length=200),
        ),
    ]
