# Generated by Django 3.1.3 on 2021-08-23 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_books_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktypes',
            old_name='booktype',
            new_name='classtype',
        ),
    ]
