# Generated by Django 3.1.3 on 2021-08-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20210823_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktypes',
            old_name='classtype',
            new_name='forgrade',
        ),
    ]
