# Generated by Django 3.1.3 on 2021-09-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20210823_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='subject',
            field=models.CharField(default='10science,11maths,12english,Main,Neet...', max_length=200),
        ),
    ]
