# Generated by Django 3.1.3 on 2021-09-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20210924_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='btype',
            new_name='bgrade',
        ),
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(default='images/tst2.jpg', upload_to=''),
        ),
    ]
