# Generated by Django 3.1.3 on 2021-09-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20210924_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='file',
            field=models.FileField(default='images/default.pdf', upload_to=''),
        ),
    ]
