# Generated by Django 3.1.3 on 2022-01-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_books_addedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
