# Generated by Django 3.1.3 on 2022-01-05 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_auto_20220105_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bgrade',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(10)]),
        ),
    ]
