# Generated by Django 3.1.3 on 2022-01-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_auto_20220105_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bgrade',
            field=models.IntegerField(default=10),
        ),
    ]
