# Generated by Django 3.1.3 on 2022-01-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_auto_20220105_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
