# Generated by Django 3.1.3 on 2022-01-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_books_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='details',
            field=models.CharField(default='details unavailable', max_length=200),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(default='book name', max_length=200),
        ),
        migrations.AlterField(
            model_name='books',
            name='review',
            field=models.CharField(default='book review', max_length=200),
        ),
    ]
