# Generated by Django 3.1.3 on 2021-09-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210824_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(default='Stud_0', max_length=500)),
                ('testname', models.CharField(default='sub_0', max_length=500)),
                ('grade', models.IntegerField()),
                ('markobtained', models.CharField(default='0', max_length=500)),
                ('totalmarks', models.CharField(default='0', max_length=500)),
                ('answersheet', models.FileField(upload_to='images')),
            ],
        ),
    ]
