# Generated by Django 3.1.3 on 2021-09-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_mockanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockanswer',
            old_name='grade',
            new_name='sgrade',
        ),
        migrations.AddField(
            model_name='mockanswer',
            name='semail',
            field=models.CharField(default='studentemail', max_length=200),
        ),
    ]
