# Generated by Django 3.1.3 on 2021-09-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210924_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockanswer',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
