# Generated by Django 3.1.3 on 2021-10-05 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_mockanswer_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockanswer',
            name='sgrade',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='qanswersheet',
            name='sgrade',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(10)]),
        ),
    ]
