# Generated by Django 3.1.3 on 2021-10-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_mockanswer_correctedanswersheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockanswer',
            name='answersheet',
            field=models.FileField(default='static/images/default.pdf', upload_to='images'),
        ),
    ]
