# Generated by Django 3.1.3 on 2021-10-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20211008_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockanswer',
            name='markobtained',
            field=models.IntegerField(default='0'),
        ),
    ]
