# Generated by Django 3.1.3 on 2022-01-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20211008_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockanswer',
            name='evaluatedby',
            field=models.CharField(default='ADMIN', max_length=1000),
        ),
    ]
