# Generated by Django 3.1.3 on 2022-03-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_mockanswer_evaluatedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qanswersheet',
            name='spoint',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
