# Generated by Django 3.1.3 on 2022-09-21 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20220307_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compexamresults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(default='studentname', max_length=200)),
                ('semail', models.CharField(default='studentemail', max_length=200)),
                ('sgrade', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(10)])),
                ('stest', models.CharField(default='testname', max_length=200)),
                ('spoint', models.CharField(default='0', max_length=200)),
                ('crt', models.CharField(default='0', max_length=200)),
                ('wrong', models.CharField(default='0', max_length=200)),
                ('sremark', models.CharField(default='remark', max_length=500)),
            ],
        ),
    ]
