# Generated by Django 3.1.3 on 2022-09-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_compexamresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='compexamresults',
            name='writting',
            field=models.BooleanField(default=True),
        ),
    ]
